api/urls.py
from django.urls import path
from api.views import BookApiView, BooksListApiView, BookListAPIView
urlpatterns = [
    path('<int:id>/', BookApiView.as_view(), name='book-api'),
    path('list/', BookListAPIView.as_view(), name='book-list'),
    path('books-list/', BooksListApiView.as_view(), name='books-list'),

]

books/urls.py
from django.urls import path
from .views import (
    BooksView, BookDetailView, AddReviewView,
    EditReviewView, ConfirmDeleteReviewView, DeleteReviewView,

)

app_name = 'books'


urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/review/', AddReviewView.as_view(), name='review'),
    path('<int:book_id>/review/<int:review_id>/edit/', EditReviewView.as_view(), name='edit-review'),
    path('<int:book_id>/review/<int:review_id>/confirm-delete/', ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path('<int:book_id>/review/<int:review_id>/delete/', DeleteReviewView.as_view(), name='delete-review')
]

goodreads/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from .views import landing_page, home_page
urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('api/', include('api.urls')),
    path('home/', home_page, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserRegistrationView, UserLoginView, UserProfileView, UserLogoutView

app_name = 'users'

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

templates/base.html
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_list_url %}
{% url 'users:profile' as user_profile_url %}
{% url 'users:logout' as user_logout_url %}
{% url 'users:login' as user_login_url %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Landing Page{% endblock %}</title>
    {% block link %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body class="mx-5">

<nav class="fixed-top navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container-fluid">
    <a class=" ms-3 me-3 navbar-brand" href="{% url 'landing_page'%}">Goodreads Clone</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{% url 'home_page' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == books_list_url %} active {% endif %}" aria-current="page" href="{% url 'books:list' %}">Books</a>
        </li>

      </ul>
        <div class="me-5">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle {% if request.path == user_profile_url %} {% endif %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ request.user.username }}
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log Out</a></li>
                      </ul>
                    </li>
                </ul>

            {% else %}
                <a class="btn btn-outline-primary {% if request.path == user_login_url %} active {% endif %}" href="{% url 'users:login' %}">Login</a>
            {% endif %}

        </div>

    </div>
  </div>
</nav>

<div class="container base">
    {% if messages %}
    <div class="mt-4">
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}" role="alert">
              {{ message }}
            </div>
        {% endfor %}
    </div>

{% endif %}
{% block content %}

{% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html'%}


{% block content %}

{% for review in page_obj %}
<div id="container">

	<div class="product-details">
		<div class="review-profile">
			<img class="small-profile-pic me-2" src="{{ review.user.profile_picture.url}}" alt="">

			<div>
			<h3 class="me-2">{{ review.user.username }}</h3>

					<i class="fa-solid fa-star gold "></i>
					<i class="fa-solid fa-star {% if review.stars_given > 1 %}gold {% endif %}"></i>
					<i class="fa-solid fa-star {% if review.stars_given > 2 %}gold {% endif %}"></i>
					<i class="fa-solid fa-star {% if review.stars_given > 3 %}gold {% endif %}"></i>
					<i class="fa-solid fa-star {% if review.stars_given > 4 %}gold {% endif %}"></i>
			</div>
		</div>
		<hr>
			<p class="information ">
				{{ review.comment | truncatechars:150 }}
			</p>



	</div>

	<div class="product-image">

		<img class="book-img" src="{{ review.book.cover_pic.url }}" alt="">


		<div class="info">
			<h2> Description</h2>
			<ul>
				<li><a href="{% url  'books:detail' review.book.id%}">{{ review.book.title}}</a></li>
				<li>{{ review.book.book_author.all.first }}</li>
			</ul>
		</div>
	</div>
</div>
<hr class="mt-1">
{% endfor %}

<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item">
      {% if page_obj.has_previous %}
      <a class="page-link" href="{% url 'home_page'%}?page={{page_obj.previous_page_number}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
      {% endif %}
    </li>
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
    <li class="page-item">
      {% if page_obj.has_next %}
      <a class="page-link" href="{% url 'home_page'%}?page={{page_obj.next_page_number}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
      {% endif %}
    </li>
  </ul>
</nav>


{% endblock %}

templates/landing.html
{% extends 'base.html' %}


{% block content %}
    <h1>Landing Page</h1>

    <span>
        Goodreads is an American social cataloging website and a subsidiary of Amazon that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.

Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler. In December 2007, the site had 650,000 members and 10,000,000 books had been added. By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees. On March 28, 2013, Amazon announced its acquisition of Goodreads, and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.
    </span>
{% endblock %}