api/urls.py
from django.urls import path
from api.views import BookApiView, BooksListApiView, BookListAPIView
urlpatterns = [
    path('<int:id>/', BookApiView.as_view(), name='book-api'),
    path('list/', BookListAPIView.as_view(), name='book-list'),
    path('books-list/', BooksListApiView.as_view(), name='books-list'),

]

books/urls.py
from django.urls import path
from .views import (
    BooksView, BookDetailView, AddReviewView,
    EditReviewView, ConfirmDeleteReviewView, DeleteReviewView,

)

app_name = 'books'


urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/review/', AddReviewView.as_view(), name='review'),
    path('<int:book_id>/review/<int:review_id>/edit/', EditReviewView.as_view(), name='edit-review'),
    path('<int:book_id>/review/<int:review_id>/confirm-delete/', ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path('<int:book_id>/review/<int:review_id>/delete/', DeleteReviewView.as_view(), name='delete-review')
]

goodreads/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from .views import landing_page, home_page
urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('api/', include('api.urls')),
    path('home/', home_page, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.utils import timezone
from functools import  reduce
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_pic = models.ImageField(default='default-book.png')
    def __str__(self):
        return self.title

    @property
    def authors(self):
        return BookAuthor.objects.filter(book=self)
    @property
    def starts(self):
        pass
        stars = Review.objects.filter(book=self)
        number = reduce(lambda x: x.stars_given, stars, 0)
        return number / stars.count()

class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class BookAuthor(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='author')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='book_author')

    def __str__(self):
        return f"{self.author}"

class Review(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='reviews')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.stars_given} by {self.user.username} for {self.book}"

books/forms.py
from django import forms
from .models import Review

class BookReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('comment',)

books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.views import View
from books.models import Book, Review
from .forms import BookReviewForm

# Create your views here.
class BooksView(View):
    def get(self, request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get('q', '')
        print(search_query)
        if search_query:
            books = books.filter(title__icontains=search_query)
        page_size = request.GET.get('page_size', 2)
        paginator = Paginator(books, page_size)
        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)

        context = {'page_obj': page_obj, 'search_query': search_query}
        return render(request, 'books/books-list.html', context)


class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        book_author = book.book_author.all()
        review_form = BookReviewForm()
        context = {
            "book": book, "review_form": review_form,
            "book_author": book_author
        }
        return render(request, "books/detail.html", context)


class AddReviewView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        stars = request.POST.get('rate')
        review_form = BookReviewForm(data=request.POST)

        if review_form.is_valid():
            Review.objects.create(
                book=book,
                user=request.user,
                stars_given=stars,
                comment=review_form.cleaned_data['comment']
            )

            return redirect(reverse("books:detail", kwargs={"id": book.id}))

        return render(request, "books/detail.html", {"book": book, "review_form": review_form})


class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.reviews.get(pk=review_id)
        if request.user != review.user:
            return redirect(reverse("books:detail", kwargs={"id": book_id}))
        review_form = BookReviewForm(instance=review)
        return render(request, 'books/edit-review.html', {'review_form': review_form})

    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.reviews.get(id=review_id)
        # if request.user == review.user:
        stars = request.POST.get('rate')
        review_form = BookReviewForm(data=request.POST)

        if review_form.is_valid():
            review.stars_given = stars
            review.comment = review_form.cleaned_data['comment']
            review.save()
            return redirect(reverse("books:detail", kwargs={"id": book_id}))

        return render(request, "books/edit-review.html", {"review_form": review_form})


class ConfirmDeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.reviews.get(id=review_id)
        if request.user != review.user:
            return redirect(reverse("books:detail", kwargs={"id": book_id}))
        return render(request, 'books/delete-review.html', {'book':book,'review':review})

class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.reviews.get(id=review_id)
        review.delete()
        messages.success(request, "Review deleted successfully")
        return redirect(reverse("books:detail", kwargs={"id": book_id}))




books/templates/books/books-list.html
{% extends 'base.html' %}

{% block title %}Books{% endblock %}

{% block content %}
  <h1>Books</h1>

<div class="row mb-3">
    <div class="col-4">
        <form class="d-flex" id="searchForm" action="{% url 'books:list' %}" method="get">
        <input type="text" id="searchInput" name="q" placeholder="Search" value="{{search_query}}">
        <button class="btn btn-danger" type="button" id="voiceButton"><i class="bi bi-mic"></i></button>
        <button class="btn btn-success" type="submit">Search</button>
    </form>

<script>
        const searchForm = document.getElementById('searchForm');
        const searchInput = document.getElementById('searchInput');
        const voiceButton = document.getElementById('voiceButton');

        voiceButton.addEventListener('click', () => {
            const recognition = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
            recognition.lang = 'en-EN';

            recognition.onstart = () => {
                console.log('Ovoz yozish boshlandi');
            };

            recognition.onend = () => {
                console.log('Ovoz yozish tugadi');
                searchForm.submit(); // Ovoz yozish tugagach, formani avtomatik jo'natish
            };

            recognition.onerror = (event) => {
                console.error('Xatolik:', event.error);
            };

            recognition.onresult = (event) => {
                const transcript = event.results[0][0].transcript;
                searchInput.value = transcript;
            };

            recognition.start();

            // 3 soniyadan keyin ovozni yozishni to'xtatish
            setTimeout(() => {
                recognition.stop();
            }, 3000);
        });
    </script>


<!--        <form class="d-flex" method="get" action="{% url 'books:list'%}">-->
<!--            {% csrf_token %}-->
<!--            <input name="q" type="text" id="searchInput" placeholder="Search">-->
<!--            <button id="searchButton">Qidirish</button>-->
<!--        </form>-->
<!--        <button class="btn btn-danger" id="voiceButton"><i class="bi bi-mic-fill"></i></button>-->
    </div>
</div>


{% if page_obj %}

{% for book in page_obj %}
    <div class="row mb-4">
        <div class="col-2 me-6">
           <img class="cover-pic" src="{{ book.cover_pic.url }}" alt="">
       </div>
        <div class="col-6 ms-4">
            <a class="book-title" href="{% url 'books:detail' book.id %}"><h3>{{ book.title }}</h3></a>
            <p>{{ book.description }}</p>
        </div>
    </div>
{% endfor %}

    <nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item">
      {% if page_obj.has_previous %}
      <a class="page-link" href="{% url 'books:list'%}?page={{page_obj.previous_page_number}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
      {% endif %}
    </li>
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
    <li class="page-item">
      {% if page_obj.has_next %}
      <a class="page-link" href="{% url 'books:list'%}?page={{page_obj.next_page_number}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
      {% endif %}
    </li>
  </ul>
</nav>

        {% else %}
            No books found.
        {% endif %}

{% endblock %}



books/templates/books/delete-review.html
{% extends 'base.html' %}
{% block content %}


    <h3>Are you sure delete this comment </h3>
    <hr>
    {{ review.comment }}
    <hr>
    <div>
        <a class="btn btn-primary" href="{% url 'books:detail' book.id %}">Cancel</a>
    <a class="btn btn-danger" href="{% url 'books:delete-review' book.id review.id %}">Delete</a>
    </div>

{% endblock %}

books/templates/books/detail.html
{% extends 'base.html '%}
{% load crispy_forms_tags %}
{% block title %}Book detail{% endblock%}
{% block content %}


    <div id="detail-page" class="row">
        <div class="col-3">
            <img class="big-cover-pic mt-2" src="{{ book.cover_pic.url }}" alt="">
        </div>
        <div class="col">
            <h3>
                {{ book.title }}
            </h3>
            <span class="fst-italic">
                Authered by
                {% for author in book_author %}
                    {% if forloop.last %}
                        {{ author }}
                    {% else %}
                        {{ author }},
                    {% endif %}
                {% endfor %}
            </span>
            <p class="book-description">
                {{ book.description }}
            </p>
        </div>


        <hr>
    <div class="row mb-4">
        <div class="col-6">
           <form method="post" action="{% url 'books:review' book.id %}">
                <div class="row mb-0">
                    <div class="stars  ps-3 mb-2 chap">
                        <input type="radio" id="five" name="rate" value="5">
                        <label for="five">
                            <i class="fa-solid fa-star"></i>
                        </label>
                        <input type="radio" id="four" name="rate" value="4">
                        <label for="four">
                            <i class="fa-solid fa-star "></i>
                        </label>
                        <input type="radio" id="three" name="rate" value="3">
                        <label for="three">
                            <i class="fa-solid fa-star"></i>
                        </label>
                        <input type="radio" id="two" name="rate" value="2">
                        <label for="two">
                            <i class="fa-solid fa-star"></i>
                        </label>
                        <input type="radio" id="one" name="rate" value="1">
                        <label for="one">
                            <i class="fa-solid fa-star"></i>
                        </label>
                    </div>
                </div>
                <div>
                    {{ review_form | crispy }}
                    {% csrf_token %}
                    <button class="btn btn-success">Add review</button>
                </div>

            </form>
        </div>
    </div>

    </div>

    {% if book.reviews.exists %}

    <h4 class="ms-5">Reviews</h4> <hr>

    {% for review in book.reviews.all %}
        <div class="row ms-3 mb-3 comment-div">
            <div class="col-1 me-5">
                <img class="small-profile-pic mb-2" src="{{ review.user.profile_picture.url }}" alt="profile pic">
                <h4 class="ms-2">{{ review.user.username }}</h4>
            </div>
            <div class="col-7 ms-5">
                <i class="fa-solid fa-star gold"></i>
                <i class="fa-solid fa-star {% if review.stars_given > 1 %}gold {% endif %}"></i>
                <i class="fa-solid fa-star {% if review.stars_given > 2 %}gold {% endif %}"></i>
                <i class="fa-solid fa-star {% if review.stars_given > 3 %}gold {% endif %}"></i>
                <i class="fa-solid fa-star {% if review.stars_given > 4 %}gold {% endif %}"></i>

                <span class="fw-lighter">{{ review.created_at }}</span>
                {% if request.user.id == review.user.id %}
                <a href="{% url 'books:edit-review' book.id review.id %}"><i class="bi bi-pencil-square"></i></a>
                <a href="{% url 'books:confirm-delete-review' book.id review.id %}"><i class="bi bi-trash"></i></a>
                {% endif %}
                <p class="mt-2 font-monospace comment-text">{{ review.comment }}</p>
            </div>
        </div>
        <hr>
    {% endfor %}
    {% endif %}
{% endblock %}

books/templates/books/edit-review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Review{% endblock %}

{% block content %}
    <div class="row mb-4">
        <div class="col-6">
           <form method="post">
                <div class="row mb-0">
                    <div class="stars  ps-3 mb-2 chap">
                        <input type="radio" id="five" name="rate" value="5">
                        <label for="five">
                            <i class="fa-solid fa-star"></i>
                        </label>
                        <input type="radio" id="four" name="rate" value="4">
                        <label for="four">
                            <i class="fa-solid fa-star "></i>
                        </label>
                        <input type="radio" id="three" name="rate" value="3">
                        <label for="three">
                            <i class="fa-solid fa-star"></i>
                        </label>
                        <input type="radio" id="two" name="rate" value="2">
                        <label for="two">
                            <i class="fa-solid fa-star"></i>
                        </label>
                        <input type="radio" id="one" name="rate" value="1">
                        <label for="one">
                            <i class="fa-solid fa-star"></i>
                        </label>
                    </div>
                </div>
                <div>
                    {{ review_form | crispy }}
                    {% csrf_token %}
                    <button class="btn btn-success">Save</button>
                </div>

            </form>
        </div>
    </div>
{% endblock %}